name: Call Other Team's Composite Action

on: push

jobs: 
  run-other-teams-stuff:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Saptarshi's Action
        uses: Saptarshi666/github-actions-basic-to-advance/.github/actions/composite@main

      - name: Kourosh's Action
        uses: kooroshsajadi/github-actions-basic-to-advance/.github/actions/composite@main
      
      - name: Gerelmaa's Action
        uses: bgerelmaa/github-actions-basic-to-advance/.github/actions/composite@main